### ISSUE TITLE
Unexpected `query->selector` behavior

### ISSUE THREAD

**Issue by vemv** [pfeodrippe/wally#4]
Hey there!

I think I lost quite some time to this:

```clj
wally.main> (query->selector :html)
".html" ;; the element selector became a class selector
```

(A real usage of mine being `(wait-for :html ,,,`)

Did I do something wrong, or should the impl be fixed?

Thanks - V

**Comment by pfeodrippe** [comment]
@vemv I will take a look on both of your issues tonight and through this weekend, thanks for the report!

We can fix the implementation, sure o/
